spring:
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true

amazon:
  access:
    key: AKIA5WGTTYKE5JFKG4WZ
    secret-key: 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
  region: eu-west-2
  end-point:
    url: dynamodb.eu-west-2.amazonaws.com

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

